apples = int(input("how many apples you want to buy: "))
total_of_apple = int(apples * 20)
oranges = int(input("how many oranges you want to buy: "))
total_of_oranges = int(oranges * 25)
print (f"total amount is {total_of_apple + total_of_oranges} ")
